name = "byeduin-vives"
compatibility_date = "2024-11-21"
pages_build_output_dir = "public"

[build]
command = "echo \"const ALADIN_TTB_KEY = '$ALADIN_TTB_KEY';\" > public/book-share/config.js"
cwd = "."

[site]
bucket = "./public"

[env.production]
routes = [
  { pattern = "byeduin.kr/*", zone_name = "byeduin.kr" }
]
